version: "3.9"

services:
  web-server:
    container_name: nginx-todo
    image: nginx:1.25
    ports:
      - "9080:80"
    volumes:
      - "./todo-frontend:/usr/share/nginx/html"
    environment:
      - TZ=Asia/Tokyo
  postgresql:
    container_name: postgres
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
