version: "3.9"

services:
  web-server:
    container_name: nginx-todo
    image: nginx:1.25
    ports:
      - "9080:80"
    volumes:
      - "./todo-frontend:/usr/share/nginx/html"
    environment:
      - TZ=Asia/Tokyo
